name: Microsoft 365 Attendance

on:
  workflow_dispatch:
  push: 
    branches: 
      - main
  schedule:
  - cron: '0 0 * * *'

jobs:
  attendance:
    runs-on: windows-latest

    env:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      DRIVE_ID: ${{ secrets.DRIVE_ID }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Microsoft Graph PowerShell
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted

          Install-Module Microsoft.Graph.Authentication -Scope CurrentUser -Force
          Install-Module Microsoft.Graph.Users -Scope CurrentUser -Force
          Install-Module Microsoft.Graph.Reports -Scope CurrentUser -Force

      - name: Run Attendance Script
        shell: pwsh
        run: |
          ./Attendance.ps1
